# --- !! IMPORTANT !! ---
# Secrets should NOT be stored directly in Git in plain text for production.
# Use tools like Sealed Secrets, HashiCorp Vault, or cloud provider secret managers.
# These values are base64 encoded placeholders. Replace with your actual encoded secrets.
# To encode: echo -n 'your_secret_value' | base64
# -----------------------
apiVersion: v1
kind: Secret
metadata:
  name: sheetapp-secrets
  namespace: sheetapp
type: Opaque
data:
  # Base64 encoded database password (e.g., 'verysecretpassword123')
  DB_PASSWORD: dmVyeXNlY3JldHBhc3N3b3JkMTIz # <-- Replace with your actual encoded password
  # Base64 encoded Django secret key (generate a strong random key)
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLSEhUkVQTEFDRV9USElTX1dJVEhfQV9SRUFMX1NUUk9OR19LRVk TISEh # <-- Replace with your actual encoded key