apiVersion: v1
kind: ConfigMap
metadata:
  name: sheetapp-config
  namespace: sheetapp
data:
  # --- Database Settings ---
  DB_ENGINE: django.db.backends.postgresql
  DB_NAME: sheetapp_db       # Matches the .env file example
  DB_USER: sheetapp_user       # Matches the .env file example
  DB_HOST: sheetapp-db-service # Internal Kubernetes service name for Postgres
  DB_PORT: "5432"

  # --- Django Settings ---
  DEBUG: "False"             # Set to False for production deployment
  DJANGO_SETTINGS_MODULE: project_config.settings # Path to Django settings

  # --- CORS Settings ---
  # Adjust origin based on your Ingress hostname/frontend URL
  CORS_ALLOWED_ORIGINS: "http://sheetapp.yourdomain.com,https://sheetapp.yourdomain.com" # <-- Replace with your actual domain(s)

  # --- Frontend Settings ---
  # This should match the internal or external URL where the backend API is accessible
  # If served via Ingress under the same domain, can be relative or absolute
  REACT_APP_API_URL: "/api" # Example relative URL if served via same Ingress
  # Or absolute: REACT_APP_API_URL: "https://sheetapp.yourdomain.com/api" # <-- Replace domain